### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by robbiepee** [sniffingpickles/Auto-Amazon-Giveaways#8]
Encountered on run.

Traceback (most recent call last):
  File "give_it_away_now.py", line 2, in <module>
    from lib.giveaway import GiveAwayBot
  File "C:\Users\robbiepee\Desktop\amazonauto\Auto-Amazon-Giveaways\lib\giveaway.py", line 11, in <module>
    from tinydb import TinyDB, Query
ModuleNotFoundError: No module named 'tinydb'

**Comment by dziban303** [comment]
You need to run the updated requirements.txt. Use the command:

    pip install -r requirements.txt

This will install the two new modules, including tinydb, required for the
bot.

**Comment by robbiepee** [comment]
Sorry, just realized that. Slipped my mind. This seems to have fixed the not-json-serializable issue. Thanks for the quick response!
