### ISSUE TITLE
I don't know if this is a problem

### ISSUE THREAD

**Issue by robbiepee** [sniffingpickles/Auto-Amazon-Giveaways#9]
I keep getting the message **** I should have clicked the prize pool?. ****
It looks like an error message

**Comment by dziban303** [comment]
I agree it's not phrased well, but it's not meant as an error message, more of a debug message I guess. The message appears when the box is clicked. I'll submit a pull request to change the verbiage. I also added code to handle giveaways requiring a follow: 

#10
